baseURL = "https://della.press"
languageCode = "en-us"
title = "Della Press"
theme = "hyde"
paginate = 8

[markup]
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1

[Menus]
  main = [
      {Name = "Search",weight = 1, URL = "search"},
      {Name = "Archives", URL = "archives"}
]

[params]
  postDir = "posts"
  layoutReverse = false
  themeColor = "theme-base-01"
  copyright = "Della Duan"
  description = "read / write / share"
  datetimeFormat = "2006/01/02 15:04:05"
 

[languages]
  [languages.en]
    title = "della.press"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = ""
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.en.params.logo]
      logoText = "della.press"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
